export const data = {
  products: [
    {
      _id: "123",
      name: "Slim shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.4,
      numReviews: 10,
    },
    {
      _id: "124",
      name: "Fit shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
    },
    {
      _id: "125",
      name: "Best pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 20,
      brand: "Nike",
      rating: 2.4,
      numReviews: 10,
    },
    {
      _id: "126",
      name: "Best pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 20,
      brand: "Nike",
      rating: 2.4,
      numReviews: 10,
    },
  ],
};
